# Generated by Django 6.0.4 on 2026-04-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
